[package]
name = "InvestDAO"
version = "1.0.1"
authors = ["Neil"]

[addresses]
dao_addr="0x1586f709246c304da42ba5c8d0679061d6cf28c348344ef0a36f23a96da76903"

[dev-addresses]

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-framework.git"
rev = "mainnet"
subdir = "aptos-framework"

[dev-dependencies]
